# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [tcl, meth]
patreon: # Replace with a single Patreon username
open_collective: # Replace with a single Open Collective username opensea.io
ko_fi: # Replace with a single Ko-fi username mouse3687
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay username leadsbridge.com
issuehunt: # Replace with a single IssueHunt username mycreed.io
otechie: # Replace with a single Otechie username united 
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['https://pornhub.com','https://vinelink.com','https;//reedsmetal.com','https://juul.com']
