image: ibuchanan/googlecloudplatform-sdk-container

pipelines:
  default:
    - step:
        script:
          # Install app & dev dependencies, test, deploy, test deployment
          - pip --quiet install -r requirements.txt -t lib/
          - echo "key = '${GOOGLE_API_KEY}'" > api_key.py
          - python test_main.py
          - echo ${GOOGLE_CLIENT_SECRET} > client-secret.json
          - gcloud auth activate-service-account --key-file client-secret.json
          - gcloud --quiet preview app deploy app.yaml --promote
          - python e2e_test.py