image: python:2.7

pipelines:
  default:
    - step:
        script:
          - GAE_PYTHONPATH=${HOME}/.cache/google_appengine
          - GOOGLE_CLOUD_SDK=${HOME}/google-cloud-sdk
          - PATH=$PATH:${GOOGLE_CLOUD_SDK}/bin
          - PYTHONPATH=${PYTHONPATH}:${GAE_PYTHONPATH}
          - CLOUDSDK_CORE_DISABLE_PROMPTS=1
          - python scripts/fetch_gae_sdk.py $(dirname "${GAE_PYTHONPATH}")
          - curl https://sdk.cloud.google.com | bash
          - pip --quiet install -r requirements.txt -t lib/
          - python test_main.py
