image: python:2.7

pipelines:
  default:
    - step:
        script:
          - GAE_PYTHONPATH=${HOME}/.cache/google_appengine
          - PATH=$PATH:${HOME}/google-cloud-sdk/bin
          - PYTHONPATH=${PYTHONPATH}:${GAE_PYTHONPATH}
          - CLOUDSDK_CORE_DISABLE_PROMPTS=1
          - python scripts/fetch_gae_sdk.py $(dirname "${GAE_PYTHONPATH}");
